# Generated by Django 4.2.16 on 2024-11-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_code', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_code', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repair_code', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('repair_type', models.CharField(choices=[('гарантійний', 'Гарантійний'), ('плановий', 'Плановий'), ('капітальний', 'Капітальний')], max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hours_needed', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.client'),
        ),
    ]
